name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - { compiler: gcc,  CC: gcc-11,   CXX: g++-11 }
          - { compiler: clang, CC: clang-16, CXX: clang++-16 }
    steps:
      - name: deps
        run: |
          echo "::group:: deps"
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
            sudo apt-get update
            sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
            sudo apt-get install kitware-archive-keyring            
            sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
            sudo apt-get update -y
            sudo apt-get install -y \
              gcc-11 \
              g++-11 \
              clang-16 \
              clang++-16 \
              cmake \
              libboost-iostreams-dev \
              nlohmann-json3-dev \
              libgtest-dev
            sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
            sudo gunzip /usr/local/bin/ninja.gz
            sudo chmod a+x /usr/local/bin/ninja
            echo "::endgroup::"

      - uses: actions/checkout@v2

      # Allow for https://github.com/nektos/act to write to the current
      # directory
      - name: fix_act
        run: |
          echo "::group:: fix_act"
          sudo chmod a+w .
          echo "::endgroup::"

      - name: configure
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          echo "::group:: configure"
          cmake -B build -G Ninja -DBUILD_IFC_READER_TESTS=ON .
          echo "::endgroup::"

      - name: build
        run: |
          echo "::group:: build"
          cmake --build build
          echo "::endgroup::"

      - name: test
        working-directory: ${{github.workspace}}/build
        run: |
          echo "::group:: test"
          ctest -C ${{env.BUILD_TYPE}}
          echo "::endgroup::"

# EOF
